# Generated by Django 4.2.7 on 2023-11-08 09:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to=core.models.product_image_path)),
            ],
        ),
    ]
